# nome do workflow que vai aparacer no github
name: Teste simulado para PR

# evento que vai disparar o workflow
on:
  pull_request:                # vai ser executado quando acionarem um pull request para a main
    branches:
      - main                  

# define os trabalhos que serão executados
jobs:
  simulacao-testes-pr:         # nome interno do job 
    runs-on: ubuntu-latest     # ambiente onde o teste será executado

    steps:                     # lista de passos a serem executadas no job simulacao-testes-pr
      - name: Clonar o código           # etapa 1: clonar o repositório do github, usando a ação oficial do github para isso
        uses: actions/checkout@v3          

      - name: Rodar testes simulados (logs)       # etapa 2: executar os testes simulados
        run: |                            
          echo "Ícone aparece quando há texto e desaparece quando vazio: OK"   # simula validação da lógica de exibição do ícone
          echo "Nenhum erro de JavaScript encontrado: OK"                      
          echo "Todos os testes simulados passaram!"                      	
